#spring.application.name=config-server
#spring.config.import=optional:config-server:http://localhost:8888
logging:
  level:
    org.springframework.cloud.config: DEBUG
spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hemanth-coder638/ecommerce-config-server
#          username: github_user_name
#          password: github_user_token
          default-label: main

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
instance:
  prefer-ip-address: true
  instance-id: ${spring.application.name}:${server.port}
