services:

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - ecommerce-network

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      EUREKA_DEFAULTZONE: http://discovery-service:8761/eureka
    depends_on:
       discovery-service:
         condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - ecommerce-network

  postgres-order:
    image: postgres:16
    container_name: postgres-order
    environment:
      POSTGRES_DB: orderDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7878
    ports:
      - "5434:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  postgres-inventory:
    image: postgres:16
    container_name: postgres-inventory
    environment:
      POSTGRES_DB: inventoryDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7878
    ports:
      - "5435:5432"
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  shipping-service:
    build: ./shipping-service
    container_name: shipping-service
    ports:
      - "4321:4321"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_DEFAULTZONE: http://discovery-service:8761/eureka
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_started
    networks:
      - ecommerce-network

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "9011:9011"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_DEFAULTZONE: http://discovery-service:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-inventory:5432/inventoryDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 7878
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_started
      postgres-inventory:
        condition: service_started
    networks:
      - ecommerce-network

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "9021:9021"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_DEFAULTZONE: http://discovery-service:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-order:5432/orderDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 7878
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_started
      postgres-order:
        condition: service_started
      inventory-service:
        condition: service_started
      shipping-service:
        condition: service_started
    networks:
      - ecommerce-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "5124:5124"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_DEFAULTZONE: http://discovery-service:8761/eureka
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_started
      order-service:
        condition: service_started
      inventory-service:
        condition: service_started
    networks:
      - ecommerce-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - ecommerce-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    container_name: logstash
    ports:
      - "5000:5000"
    volumes:
      - ./docker-files/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - ecommerce-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - ecommerce-network
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - ecommerce-network

volumes:
  order-db-data:
  inventory-db-data:
  elasticsearch-data:

networks:
  ecommerce-network: